apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mucoso
  name: mucoso
spec:
  containers:
    - image: nginx
      name: mucoso
      ports:
      - containerPort: 80
      resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: Always
status: {} 
